#!/bin/sh 

alias config='/usr/bin/git --git-dir=/home/sloth/.cfg/ --work-tree=/home/sloth'

alias ls='ls --color=auto'
alias esyn='doas emaint -a sync'
alias ein='doas emerge --ask'
alias eup='doas emerge -uDU --keep-going --with-bdeps=y --ask @world'
alias equ='equery uses'
alias erm='doas emerge --deselect'
alias edc='doas emerge --depclean -v'

alias mp3="youtube-dl -x --embed-thumbnail --audio-format mp3"

alias zzz='doas s2ram -f'
alias reboot='doas reboot'
alias sd='doas shutdown -P now'

alias vi='nvim'
alias tmux='tmux -f ${HOME}/.config/tmux/.tmux.conf'


# Functions

fe() {
  local files
  IFS=$'\n' files=($(fzf-tmux --query="$1" --multi --select-1 --exit-0))
  [[ -n "$files" ]] && ${EDITOR:-vim} "${files[@]}"
}

fkill() {
    local pid 
    if [ "$UID" != "0" ]; then
        pid=$(ps -f -u $UID | sed 1d | fzf -m | awk '{print $2}')
    else
        pid=$(ps -ef | sed 1d | fzf -m | awk '{print $2}')
    fi  

    if [ "x$pid" != "x" ]
    then
        echo $pid | xargs kill -${1:-9}
    fi  
}
