#!/bin/sh 

alias ls='ls --color=auto'
alias xin='sudo xbps-install -S'
alias xup='sudo xbps-install -Suv'
alias xq='sudo xbps-query'
alias xf='sudo xbps-query -Rs'
alias xme='sudo xbps-query -m'
alias xrm='sudo xbps-remove -R'
alias xcp='sudo xbps-remove -Oo'

alias mp3="youtube-dl -x --embed-thumbnail --audio-format mp3"

alias config='/usr/bin/git --git-dir=/home/sloth/.cfg/ --work-tree=/home/sloth'

alias zzz='sudo zzz'
alias reboot='sudo reboot'
alias poweroff='sudo poweroff'

alias vi='nvim'
alias tmux='tmux -f ${HOME}/.config/tmux/.tmux.conf'


# Functions

fe() {
  local files
  IFS=$'\n' files=($(fzf-tmux --query="$1" --multi --select-1 --exit-0))
  [[ -n "$files" ]] && ${EDITOR:-vim} "${files[@]}"
}

fkill() {
    local pid 
    if [ "$UID" != "0" ]; then
        pid=$(ps -f -u $UID | sed 1d | fzf -m | awk '{print $2}')
    else
        pid=$(ps -ef | sed 1d | fzf -m | awk '{print $2}')
    fi  

    if [ "x$pid" != "x" ]
    then
        echo $pid | xargs kill -${1:-9}
    fi  
}
