#!/bin/sh 

alias dotfiles='/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME'

alias ls='ls --color=auto'
alias xin='doas xbps-install -S'
alias xup='doas xbps-install -Suv'
alias xq='doas xbps-query'
alias xf='doas xbps-query -Rs'
alias xme='doas xbps-query -m'
alias xrm='doas xbps-remove -R'
alias xcp='doas xbps-remove -Oo'

alias mp3="youtube-dl -x --embed-thumbnail --audio-format mp3"

alias zzz='doas zzz'
alias reboot='doas reboot'
alias poweroff='doas poweroff'

alias vi='nvim'
alias tmux='tmux -f ${HOME}/.config/tmux/.tmux.conf'
alias nnn='nnn -e'

alias rt='rtorrent -d /mnt/storage/downloads'


# Functions

fe() {
  local files
  IFS=$'\n' files=($(fzf-tmux --query="$1" --multi --select-1 --exit-0))
  [[ -n "$files" ]] && ${EDITOR:-vim} "${files[@]}"
}

fkill() {
    local pid 
    if [ "$UID" != "0" ]; then
        pid=$(ps -f -u $UID | sed 1d | fzf -m | awk '{print $2}')
    else
        pid=$(ps -ef | sed 1d | fzf -m | awk '{print $2}')
    fi  

    if [ "x$pid" != "x" ]
    then
        echo $pid | xargs kill -${1:-9}
    fi  
}
