#! /bin/sh

sxhkd &

bspc wm -O HDMI1 HDMI2

bspc monitor HDMI1 -d I II III
bspc monitor HDMI2 -d IV V VI

$HOME/.screenlayout/dual.sh

setxkbmap -layout us altgr-intl

feh --bg-scale $HOME/.config/bspwm/wallpaper.jpg

# Set the border colors.
bspc config normal_border_color "#2e3440"
bspc config active_border_color "#d8dee9"
bspc config focused_border_color "#88c0d0"
bspc config presel_feedback_color "#88c0d0"

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true

bspc rule -a Zathura state=tiled

$HOME/.config/polybar/launch.sh &
picom -bc &

pgrep bspswallow || bspswallow &
