#! /bin/sh

sxhkd &
pipewire &
easyeffects --gapplication-service &
$HOME/.screenlayout/dual.sh

bspc wm -O HDMI-A-0 DVI-D-0

bspc monitor HDMI-A-0 -d I II III IV
bspc monitor DVI-D-0 -d V VI VII VIII


setxkbmap -layout us altgr-intl

xwallpaper --stretch $HOME/.config/bspwm/wallpaper.jpg

# Set the border colors.
bspc config normal_border_color "#4c566a"
bspc config active_border_color "#81a1c1"
bspc config focused_border_color "#a3be8c"
bspc config presel_feedback_color "#88c0d0"

bspc config border_width         3
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   false

bspc rule -a Zathura state=tiled

$HOME/.config/polybar/launch.sh &
picom --experimental-backends -bc --config $HOME/.config/picom/config &
dunst &
