#! /bin/sh

sxhkd &
pipewire &
easyeffects --gapplication-service &
$HOME/.config/.screenlayout/dual.sh
/usr/libexec/polkit-gnome-authentication-agent-1 &

bspc monitor DisplayPort-0 -d I II III IV V VI
bspc monitor HDMI-A-0 -d VII VIII

enforce_monitor_position DisplayPort-0 '^1' &

setxkbmap -layout us altgr-intl

xwallpaper --stretch $HOME/.config/bspwm/wallpaper.jpg

bspc config remove_unplugged_monitors false 
bspc config remove_disabled_monitors false 

# Set the border colors.
bspc config normal_border_color "#4c566a"
bspc config active_border_color "#88c0d0"
bspc config focused_border_color "#8fbcbb"
bspc config presel_feedback_color "#88c0d0"

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   false

bspc rule -a Zathura state=tiled

$HOME/.config/polybar/launch.sh &
picom --experimental-backends -bc --config $HOME/.config/picom/config &
dunst &
syncthing &
